### ISSUE TITLE
Thanks me Later!

### ISSUE THREAD

**Issue by REVxRETRO** [rumbleFTW/lung-cancer-detection#1]
Under the section "Example: Prediction Vs Truth" in your Notebook.ipynb, the Truth label for all the images are not correct since you have return the statement _`"Truth : (int(batch[1][0]))"`_ this will give you the True label only for the First indexed image so, it should be  _`"Truth : (int(batch[1][i]))"`_

**Comment by rumbleFTW** [comment]
@AnkitPl778 Thank you for pointing-out the error. This error went unnoticed for such a long time. You can write a PR that solves this issue if you want. Else I will fix it later when I have time.

**Comment by REVxRETRO** [comment]
Yeah, Sure I'll do.

**Comment by rumbleFTW** [comment]
#3 Solves this issue. So this issue is marked as fixed. Thank you for your contribution @AnkitPl778.
